### ISSUE TITLE
Conversation with Johan Norberg

### ISSUE THREAD

**Issue by semioticrobotic** [open-organization/video#2]
Members of the Open Organization community chat with Johan Norberg, author of the book *Open*, for OpenOrgTV.

**Comment by semioticrobotic** [comment]
I haven't looked at the email thread in a few days, because I lost access to it recently. However, I _think_ I wrote to everyone to initiate a conversation about scheduling and deferring to @jimmysjolund's schedule as priority. But I'll be honest and say that could be an entirely fabricated memory and I'd need to resume the email conversation again. If you could please respond to it and ensure my address is attached to it, we can pick it up again.

**Comment by jimmysjolund** [comment]
I didn't catch that in the email but see it was in there, sorry about that. Also forwarded to @semioticrobotic new email.

**Comment by jimmysjolund** [comment]
Reached out to Johan to match calendars.

**Comment by semioticrobotic** [comment]
Back in the loop! Thanks, @jimmysjolund.

**Comment by RonMcFarland** [comment]
Great.

Looking forward to it.

Ron

**Comment by jimmysjolund** [comment]
Bluejeans invitation sent out today.

**Comment by RonMcFarland** [comment]
Jimmy,

Could you send me a link to it when you get a chance?

Thanks,

Ron

**Comment by jimmysjolund** [comment]
I used your gmail address and the invitation was sent out from Bluejeans. Didn't you get that one? It's the first time I'm using Bluejeans so maybe I didn't do all the steps right.

**Comment by RonMcFarland** [comment]
Got it.

**Comment by semioticrobotic** [comment]
I've got it and confirmed! Thanks so much, @jimmysjolund! You rock.

**Comment by jimmysjolund** [comment]
Planned publish date 15th of June.

**Comment by semioticrobotic** [comment]
### Promotion checklist

- [ ] Discourse
- [ ] Twitter
- [ ] LinkedIn

**Comment by RonMcFarland** [comment]
Hi all,

I think there will be at least four of us for this discussion and in three
very different timezones with me in Tokyo.  Therefore, best would probably
be morning in the US, midday in Europe and evening in Tokyo where I am.

Looking forward to seeing what is best for all of us.

Best wishes,

Ron McFarland
Tokyo, Japan

**Comment by jimmysjolund** [comment]
This has already been recorded and published. I'm closing it again. Did you perhaps intend for Team of Teams?

**Comment by RonMcFarland** [comment]
Jimmy,

The Team of Teams articles are still going through final publishing.  The
two articles have not been published to my understanding.  After that, I
think we should explore a YouTube recording.

This is different than the Open Societies discussion.

Thanks,

Ron

**Comment by RonMcFarland** [comment]
Jimmy,

No.  I am thinking of doing a video just with us on a different subject,
namely how to make an Open Organization Chart.  I still have to get those
articles published first.  AmyJune is working on the editing and publishing
of them.

Sorry for the confusion.

**Comment by RonMcFarland** [comment]
The discussion with Johan is closed.

**Comment by semioticrobotic** [comment]
In that case, @RonMcFarland, you will want to create [a new issue in our backlog of ideas](https://github.com/open-organization/video/issues), so we can get this onto Jimmy's radar and into his video pipeline.
