### ISSUE TITLE
Promo videos for each book

### ISSUE THREAD

**Issue by jenkelchner** [open-organization/video#3]
Creating simple text video to showcase each book in our community series to house in our YouTube Channel

I'll be working on creating these quick promos during July.

- [ ] Workbook
- [x] Leadership Manual
- [ ] Field Guide
- [ ] Educators Guide
- [ ] Human at a Distance
- [ ] IT Culture Change

**Comment by jimmysjolund** [comment]
We are breaking out each book as a separate issue, closing this one.
