### ISSUE TITLE
Roundtable discussion 'Team of Teams'

### ISSUE THREAD

**Issue by jimmysjolund** [open-organization/video#44]
Following the book review article.

**Comment by jimmysjolund** [comment]
Following the two articles:
https://opensource.com/article/22/10/innovative-open-organization-chart-works
https://opensource.com/article/22/10/innovative-open-organization-chart

we are planning to host a roundtable discussion to be recorded and published on OpenOrgTV.

**Comment by semioticrobotic** [comment]
I'll let you and Ron determine the day and time that works best for you both. After you have, I'll check to see if I'm available during your session. Happy to participate if available, but this way I'm not a blocker to getting it done.

**Comment by jimmysjolund** [comment]
A suggestion would be 1st of Dec at 14:00 CET. Thoughts? @ronmcfarland

**Comment by RonMcFarland** [comment]
I made a note of that date and time.

Ron

**Comment by semioticrobotic** [comment]
Glad you could work out a time, @jimmysjolund and @RonMcFarland! Unfortunately I'll be out of town that day and away from my computer, so I won't be able to join. But perhaps someone else would like to participate?

**Comment by jimmysjolund** [comment]
I'm open for other dates as well, this was just the first one I came up with.

**Comment by jimmysjolund** [comment]
How about 7 Dec 14:00 CET?

**Comment by RonMcFarland** [comment]
December 7 at my 10pm in Tokyo is OK for me.  I made a note of it.

Ron in Tokyo

**Comment by HeidiHVL** [comment]
It's 8am ET so that works for me! I will have 45mins because I need to drive into the office. I'm blocking my calendar while we wait on confirmation/declination from BB.

**Comment by semioticrobotic** [comment]
Unfortunately I won't be able to make that day. But it seems like you've all got this well in hand! And I'm looking forward to watching the episode.

**Comment by RonMcFarland** [comment]
Is that date confirmed now?  December 7th, 2pm for Jimmy, 10pm for Ron, 8am
for Heidi.

Should just the three of use have the discussion?  I can start with my
presentation which I shared with you, and we can have discussions along the
way.  Also, Jimmy, I think you contacted the author or one of his staff.
Should they be invited?

Cheers,

Ron

**Comment by jimmysjolund** [comment]
I'll send out an Google Meet invitation. Let me know if Bluejeans is preferred.

**Comment by jimmysjolund** [comment]
I was only in contact with Stanley's company to check with the pictures we might use. They were curious about the presentation but had no objections for fair use or wanting to join the discussion.

**Comment by jimmysjolund** [comment]
Recorded as planned on the 7th of December. Going into editing as soon as I can.

**Comment by RonMcFarland** [comment]
Jimmy,

Thank you for the organization of this gathering.  I think it went pretty
well, and we covered all the important topics we wanted to bring out.

No hurry on the editing as far as I'm concerned.

Cheers,

Ron

**Comment by jimmysjolund** [comment]
Published today: https://youtu.be/Kgnft8MkrKw

**Comment by RonMcFarland** [comment]
Awesome, thanks!
