### ISSUE TITLE
Need to migrate the classic Project to "new" Project

### ISSUE THREAD

**Issue by jimmysjolund** [open-organization/video#47]
> Projects (classic) will be sunset on August 23, 2024

**Comment by semioticrobotic** [comment]
I tried to take care of this one, @jimmysjolund, but I get the sense that we're already using the "new" project system for this one. Maybe I'm just missing something?

**Comment by jimmysjolund** [comment]
I think all existing projects have been migrated. Perhaps I missed updating this issue.

**Comment by semioticrobotic** [comment]
Yes, I believe we're good!
